[Unit]
Conflicts=direwolf.service
After=network-online.target gpsd.service
Wants=network-online.target
StartLimitIntervalSec=0

[Service]
ExecStart=
ExecStart=/usr/bin/graywolf -config /var/lib/graywolf/graywolf.db -history-db /run/graywolf/history.db -tile-cache-dir /var/lib/graywolf/tiles -modem /usr/bin/graywolf-modem -http @GRAYWOLF_HTTP_LISTEN@
RuntimeDirectory=graywolf
RuntimeDirectoryMode=0750
RuntimeDirectoryPreserve=yes
Restart=on-failure
RestartSec=5s
