[Unit]
After=network-online.target gpsd.service pcs-aprs-kiss-firewall.service
Wants=network-online.target
Requires=pcs-aprs-kiss-firewall.service

[Service]
ExecStart=
ExecStart=@DIREWOLF_BIN@ -c /etc/direwolf.conf
Restart=on-failure
RestartSec=5s
