#!/usr/bin/env bash

set -Eeuo pipefail

export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:${PATH:-}"

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INSTALL_CONFIG="${PCS_INSTALL_CONFIG:-${REPO_DIR}/config/pcs-install.conf}"
APRS_CONFIG_DIR="/etc/pcs/aprs"
STAGED_MARKER="${APRS_CONFIG_DIR}/graywolf-staged"
ACTIVE_MARKER="${APRS_CONFIG_DIR}/graywolf-active"
PROFILE_SRC="${REPO_DIR}/scripts/pcs-graywolf-profile.py"
PROFILE_DST="/usr/local/sbin/pcs-graywolf-profile"
GRAYWOLF_OVERRIDE_SRC="${REPO_DIR}/systemd/pcs-graywolf-override.conf"
GRAYWOLF_OVERRIDE_DST="/etc/systemd/system/graywolf.service.d/pcs.conf"
KISS_FIREWALL_CONFIG="${APRS_CONFIG_DIR}/kiss-firewall.conf"
PTT_SAFE_SRC="${REPO_DIR}/scripts/pcs-aprs-ptt-safe.sh"
PTT_SAFE_DST="/usr/local/sbin/pcs-aprs-ptt-safe"
PTT_SAFE_SERVICE_SRC="${REPO_DIR}/systemd/pcs-aprs-ptt-safe.service"
PTT_SAFE_SERVICE_DST="/etc/systemd/system/pcs-aprs-ptt-safe.service"
PTT_WATCHDOG_SRC="${REPO_DIR}/scripts/pcs-aprs-ptt-watchdog.sh"
PTT_WATCHDOG_DST="/usr/local/sbin/pcs-aprs-ptt-watchdog"
PTT_WATCHDOG_SERVICE_SRC="${REPO_DIR}/systemd/pcs-aprs-ptt-watchdog.service"
PTT_WATCHDOG_SERVICE_DST="/etc/systemd/system/pcs-aprs-ptt-watchdog.service"
PTT_SAFE_CONFIG="${APRS_CONFIG_DIR}/ptt-safe.conf"
GRAYWOLF_VERSION="0.14.13"
GRAYWOLF_RELEASE_BASE="https://github.com/chrissnell/graywolf/releases/download/v${GRAYWOLF_VERSION}"
MODE="${1:---prepare}"

if [[ -f "${INSTALL_CONFIG}" ]]; then
    # shellcheck source=/dev/null
    source "${INSTALL_CONFIG}"
fi

PCS_SETUP_APRS="${PCS_SETUP_APRS:-no}"
PCS_APRS_ENGINE="${PCS_APRS_ENGINE:-graywolf}"
PCS_APRS_ENGINE_STAGED="${PCS_APRS_ENGINE_STAGED:-}"
PCS_GRAYWOLF_HTTP_ADDRESS="${PCS_GRAYWOLF_HTTP_ADDRESS:-10.42.0.1}"
PCS_GRAYWOLF_HTTP_PORT="${PCS_GRAYWOLF_HTTP_PORT:-8070}"
PCS_APRS_PTT_GPIO_LINE="${PCS_APRS_PTT_GPIO_LINE:-6}"
PCS_APRS_CALLSIGN="${PCS_APRS_CALLSIGN:-}"
PCS_APRS_ACTIVE_MODE="${PCS_APRS_ACTIVE_MODE:-tx}"

usage() {
    cat <<'EOF'
Usage: ./scripts/setup-graywolf-aprs.sh COMMAND

  --prepare       Install the pinned Graywolf package and PCS service override.
                  Graywolf remains stopped and disabled with no radio profile.
  --check         Report package, service, marker, port, and mutual-exclusion state.
  --capabilities  Report the installed Graywolf version and PCS-required interfaces.
  --activate      Transactionally replace Dire Wolf with the commissioned Graywolf profile.
  --rollback-direwolf
                  Stop Graywolf, restore its pre-activation database, and restart Dire Wolf.
  -h, --help      Show this help.

--prepare stages software only. --activate can enable scheduled RF transmission
after the typed callsign confirmation and all PCS prerequisite checks pass.
EOF
}

require_normal_user() {
    if [[ "${EUID}" -eq 0 ]]; then
        echo "ERROR: Do not run this script with sudo." >&2
        echo "Run it as the normal Pi user; it requests sudo only where needed." >&2
        exit 1
    fi
}

ensure_sudo() {
    if ! sudo -n true 2>/dev/null; then
        sudo -v
    fi
}

set_install_config_value() {
    local key="$1"
    local value="$2"
    local config_dir
    local temp_file

    config_dir="$(dirname "${INSTALL_CONFIG}")"
    mkdir -p "${config_dir}"
    temp_file="$(mktemp "${config_dir}/.pcs-install.XXXXXX")"
    if [[ -f "${INSTALL_CONFIG}" ]]; then
        awk -v key="${key}" -v value="${value}" '
            BEGIN { replaced=0 }
            $0 ~ "^[[:space:]]*" key "=" {
                printf "%s=%c%s%c\n", key, 34, value, 34
                replaced=1
                next
            }
            { print }
            END { if (!replaced) printf "%s=%c%s%c\n", key, 34, value, 34 }
        ' "${INSTALL_CONFIG}" >"${temp_file}"
    else
        {
            echo "# PCS install config"
            echo "# Generated by scripts/setup-graywolf-aprs.sh"
            printf '%s="%s"\n' "${key}" "${value}"
        } >"${temp_file}"
    fi
    chmod 0600 "${temp_file}"
    mv -f -- "${temp_file}" "${INSTALL_CONFIG}"
}

set_privileged_config_value() {
    local file="$1"
    local key="$2"
    local value="$3"
    local temp_file

    temp_file="$(mktemp)"
    if sudo test -f "${file}"; then
        sudo cat "${file}" >"${temp_file}"
    fi
    awk -v key="${key}" -v value="${value}" '
        BEGIN { replaced=0 }
        $0 ~ "^[[:space:]]*" key "=" {
            printf "%s=%s\n", key, value
            replaced=1
            next
        }
        { print }
        END { if (!replaced) printf "%s=%s\n", key, value }
    ' "${temp_file}" >"${temp_file}.new"
    sudo install -o root -g root -m 0640 "${temp_file}.new" "${file}"
    rm -f -- "${temp_file}" "${temp_file}.new"
}

validate_http_endpoint() {
    local octet

    if [[ ! "${PCS_GRAYWOLF_HTTP_ADDRESS}" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; then
        echo "ERROR: PCS_GRAYWOLF_HTTP_ADDRESS must be a literal IPv4 address." >&2
        return 1
    fi
    IFS='.' read -r -a address_octets <<<"${PCS_GRAYWOLF_HTTP_ADDRESS}"
    for octet in "${address_octets[@]}"; do
        if (( 10#${octet} > 255 )); then
            echo "ERROR: PCS_GRAYWOLF_HTTP_ADDRESS contains an invalid IPv4 octet." >&2
            return 1
        fi
    done
    if [[ ! "${PCS_GRAYWOLF_HTTP_PORT}" =~ ^[0-9]+$ ]] \
        || (( PCS_GRAYWOLF_HTTP_PORT < 1024 || PCS_GRAYWOLF_HTTP_PORT > 65535 )); then
        echo "ERROR: PCS_GRAYWOLF_HTTP_PORT must be between 1024 and 65535." >&2
        return 1
    fi
    if (( PCS_GRAYWOLF_HTTP_PORT == 8080 )); then
        echo "ERROR: tcp/8080 is reserved by the PCS legacy admin redirect." >&2
        return 1
    fi
}

package_for_architecture() {
    local architecture
    architecture="$(dpkg --print-architecture)"
    case "${architecture}" in
        amd64)
            printf '%s\t%s\n' "graywolf_${GRAYWOLF_VERSION}_amd64.deb" "660e79f0d0779575fb049506dc05a1d96799c697a0c94598cbf7eaf64dd98360"
            ;;
        arm64)
            printf '%s\t%s\n' "graywolf_${GRAYWOLF_VERSION}_arm64.deb" "1c85cb35e8ffbf364aa7fccc4b62f2c344e847739f4323ba5fac663de7167ed7"
            ;;
        armhf)
            printf '%s\t%s\n' "graywolf_${GRAYWOLF_VERSION}_armhf.deb" "4885291f0138c9417ffef415d0f473c451d68742ccdd4f9cb3951dcc5fd933fa"
            ;;
        *)
            echo "ERROR: Graywolf ${GRAYWOLF_VERSION} has no pinned PCS package for ${architecture}." >&2
            return 1
            ;;
    esac
}

show_check() {
    local installed="no"
    local active
    local enabled
    local direwolf_active

    active="$(systemctl is-active graywolf.service 2>/dev/null || true)"
    enabled="$(systemctl is-enabled graywolf.service 2>/dev/null || true)"
    direwolf_active="$(systemctl is-active direwolf.service 2>/dev/null || true)"
    command -v graywolf >/dev/null 2>&1 && installed="yes"

    echo "APRS engine:            ${PCS_APRS_ENGINE}"
    echo "Graywolf installed:     ${installed}"
    if [[ "${installed}" == "yes" ]]; then
        echo "Graywolf version:       $(graywolf version 2>/dev/null || true)"
    fi
    echo "Graywolf service:       ${active:-unknown}"
    echo "Graywolf boot state:    ${enabled:-unknown}"
    echo "Dire Wolf service:      ${direwolf_active:-unknown}"
    echo "PCS staged marker:      $([[ -f "${STAGED_MARKER}" ]] && echo present || echo missing)"
    echo "PCS Graywolf endpoint:  ${PCS_GRAYWOLF_HTTP_ADDRESS}:${PCS_GRAYWOLF_HTTP_PORT}"

    if [[ "${installed}" == "yes" && "${active}" != "active" && "${enabled}" != "enabled" \
        && -f "${STAGED_MARKER}" \
        && ( ( "${PCS_SETUP_APRS}" == "staged" && "${PCS_APRS_ENGINE}" == "graywolf" ) \
            || ( "${PCS_APRS_ENGINE_STAGED}" == "graywolf" && "${direwolf_active}" == "active" ) ) ]]; then
        echo "State is correct for hardware-safe Graywolf staging."
    fi
}

show_capabilities() {
    if ! command -v graywolf >/dev/null 2>&1 || ! command -v graywolf-modem >/dev/null 2>&1; then
        echo "ERROR: Graywolf is not installed." >&2
        return 1
    fi
    graywolf version
    echo "PCS-required Graywolf interfaces: ALSA audio, AFSK 1200, Linux gpiochip PTT, gpsd, KISS TCP, AGWPE, Prometheus metrics"
    echo "Graywolf modem binary: $(command -v graywolf-modem)"
}

prepare() {
    local aprs_group
    local package_record
    local package_name
    local package_sha256
    local temp_dir
    local rendered_override
    local ptt_safe_env

    require_normal_user
    validate_http_endpoint
    ensure_sudo

    if [[ ! -f "${GRAYWOLF_OVERRIDE_SRC}" || ! -f "${PTT_SAFE_SRC}" \
        || ! -f "${PTT_SAFE_SERVICE_SRC}" || ! -f "${PTT_WATCHDOG_SRC}" \
        || ! -f "${PTT_WATCHDOG_SERVICE_SRC}" || ! -f "${PROFILE_SRC}" ]]; then
        echo "ERROR: PCS Graywolf runtime support files are missing from the repository." >&2
        return 1
    fi

    if systemctl is-active --quiet graywolf.service 2>/dev/null; then
        echo "ERROR: graywolf.service is already active; --prepare never changes an active radio service." >&2
        return 1
    fi
    package_record="$(package_for_architecture)"
    IFS=$'\t' read -r package_name package_sha256 <<<"${package_record}"
    temp_dir="$(mktemp -d)"
    trap 'rm -rf -- "${temp_dir}"' EXIT

    echo "Downloading pinned Graywolf ${GRAYWOLF_VERSION} package..."
    curl --fail --location --proto '=https' --tlsv1.2 \
        --output "${temp_dir}/${package_name}" "${GRAYWOLF_RELEASE_BASE}/${package_name}"
    printf '%s  %s\n' "${package_sha256}" "${temp_dir}/${package_name}" | sha256sum --check --status

    echo "Installing Graywolf; the verified package enables but does not start its service..."
    sudo apt-get install -y gpiod "${temp_dir}/${package_name}"
    sudo systemctl disable --now graywolf.service >/dev/null 2>&1 || true

    rendered_override="${temp_dir}/pcs-graywolf-override.conf"
    sed "s|@GRAYWOLF_HTTP_LISTEN@|${PCS_GRAYWOLF_HTTP_ADDRESS}:${PCS_GRAYWOLF_HTTP_PORT}|g" \
        "${GRAYWOLF_OVERRIDE_SRC}" >"${rendered_override}"
    sudo install -d -o root -g root -m 0755 "$(dirname "${GRAYWOLF_OVERRIDE_DST}")"
    sudo install -o root -g root -m 0644 "${rendered_override}" "${GRAYWOLF_OVERRIDE_DST}"
    aprs_group="graywolf"
    if getent group direwolf >/dev/null 2>&1; then
        aprs_group="direwolf"
    fi
    sudo install -d -o root -g "${aprs_group}" -m 0750 "${APRS_CONFIG_DIR}"
    ptt_safe_env="${temp_dir}/ptt-safe.conf"
    printf 'PCS_APRS_PTT_CHIP=%q\nPCS_APRS_PTT_LINE=%q\n' \
        "gpiochip0" "${PCS_APRS_PTT_GPIO_LINE}" >"${ptt_safe_env}"
    sudo install -o root -g root -m 0755 "${PTT_SAFE_SRC}" "${PTT_SAFE_DST}"
    sudo install -o root -g root -m 0644 "${PTT_SAFE_SERVICE_SRC}" "${PTT_SAFE_SERVICE_DST}"
    sudo install -o root -g root -m 0755 "${PTT_WATCHDOG_SRC}" "${PTT_WATCHDOG_DST}"
    sudo install -o root -g root -m 0644 "${PTT_WATCHDOG_SERVICE_SRC}" "${PTT_WATCHDOG_SERVICE_DST}"
    sudo install -o root -g root -m 0644 "${ptt_safe_env}" "${PTT_SAFE_CONFIG}"
    printf 'graywolf=%s\nhttp=%s:%s\nstate=staged\n' \
        "${GRAYWOLF_VERSION}" "${PCS_GRAYWOLF_HTTP_ADDRESS}" "${PCS_GRAYWOLF_HTTP_PORT}" \
        | sudo tee "${STAGED_MARKER}" >/dev/null
    sudo chmod 0644 "${STAGED_MARKER}"
    set_privileged_config_value "${KISS_FIREWALL_CONFIG}" \
        "PCS_APRS_GRAYWOLF_HTTP_PORT" "${PCS_GRAYWOLF_HTTP_PORT}"
    sudo systemctl daemon-reload
    sudo systemctl enable --now pcs-aprs-ptt-watchdog.service

    set_install_config_value "PCS_APRS_ENGINE_STAGED" "graywolf"
    PCS_APRS_ENGINE_STAGED="graywolf"
    if ! systemctl is-active --quiet direwolf.service 2>/dev/null; then
        set_install_config_value "PCS_APRS_ENGINE" "graywolf"
        set_install_config_value "PCS_SETUP_APRS" "staged"
        PCS_APRS_ENGINE="graywolf"
        PCS_SETUP_APRS="staged"
        sudo systemctl enable --now pcs-aprs-ptt-safe.service
    fi

    rm -rf -- "${temp_dir}"
    trap - EXIT
    show_check
    echo
    echo "Graywolf software staging complete. The active APRS engine was not stopped or replaced."
    echo "No account, callsign, APRS-IS, audio, GPS, PTT, beacon, digipeater, service start, or RF TX was configured."
}

wait_for_graywolf_api() {
    local attempt
    for attempt in {1..50}; do
        if curl -sS --max-time 2 -o /dev/null \
            "http://${PCS_GRAYWOLF_HTTP_ADDRESS}:${PCS_GRAYWOLF_HTTP_PORT}/api/health" >/dev/null 2>&1; then
            return 0
        fi
        sleep 0.2
    done
    echo "ERROR: Graywolf health API did not become ready." >&2
    return 1
}

install_activation_support() {
    sudo install -o root -g root -m 0755 "${PROFILE_SRC}" "${PROFILE_DST}"
    sudo install -o root -g root -m 0755 "${PTT_WATCHDOG_SRC}" "${PTT_WATCHDOG_DST}"
    sudo install -o root -g root -m 0644 "${PTT_WATCHDOG_SERVICE_SRC}" "${PTT_WATCHDOG_SERVICE_DST}"
    sudo systemctl daemon-reload
    sudo systemctl enable --now pcs-aprs-ptt-watchdog.service
}

activate() {
    local backup_dir="/var/backups/pcs-aprs"
    local backup_file=""
    local confirmation="${PCS_GRAYWOLF_ACTIVATE_CONFIRM:-}"
    local expected="ENABLE-RF-${PCS_APRS_CALLSIGN}"
    local timestamp

    require_normal_user
    validate_http_endpoint
    ensure_sudo
    if [[ -z "${PCS_APRS_CALLSIGN}" ]]; then
        echo "ERROR: PCS_APRS_CALLSIGN is required for Graywolf activation." >&2
        return 1
    fi
    if [[ "${PCS_APRS_ACTIVE_MODE}" != "tx" ]]; then
        echo "ERROR: the commissioned Graywolf replacement currently requires PCS_APRS_ACTIVE_MODE=tx." >&2
        return 1
    fi
    if [[ "${confirmation}" != "${expected}" ]]; then
        if [[ ! -t 0 ]]; then
            echo "ERROR: set PCS_GRAYWOLF_ACTIVATE_CONFIRM=${expected} for authorized non-interactive activation." >&2
            return 1
        fi
        echo "Graywolf activation enables the GPS beacon, fill-in digipeater, and two-way iGate on RF."
        read -r -p "Type ${expected} to continue: " confirmation
        [[ "${confirmation}" == "${expected}" ]] || { echo "Activation cancelled."; return 1; }
    fi
    command -v graywolf >/dev/null 2>&1 && command -v graywolf-modem >/dev/null 2>&1 \
        || { echo "ERROR: Graywolf binaries are missing." >&2; return 1; }
    sudo test -s /var/lib/graywolf/graywolf.db \
        || { echo "ERROR: Graywolf staged profile database is missing." >&2; return 1; }
    systemctl is-active --quiet gpsd.service \
        || { echo "ERROR: gpsd.service is not active." >&2; return 1; }
    sudo /usr/local/sbin/pcs-sa818 --config /etc/pcs/aprs/sa818.ini --check >/dev/null
    sudo /usr/local/sbin/pcs-aprs-audio --check >/dev/null
    sudo /usr/local/sbin/pcs-aprs-kiss-firewall --check >/dev/null

    install_activation_support
    timestamp="$(date -u +%Y%m%dT%H%M%SZ)"
    sudo install -d -o root -g root -m 0700 "${backup_dir}"
    backup_file="${backup_dir}/graywolf.db.pre-activation.${timestamp}"
    sudo install -o root -g root -m 0600 /var/lib/graywolf/graywolf.db "${backup_file}"

    sudo systemctl disable --now direwolf.service >/dev/null 2>&1 || true
    sudo systemctl mask direwolf.service >/dev/null
    sudo systemctl unmask graywolf.service >/dev/null
    if ! sudo systemctl start graywolf.service || ! wait_for_graywolf_api \
        || ! sudo "${PROFILE_DST}" activate \
            --base-url "http://${PCS_GRAYWOLF_HTTP_ADDRESS}:${PCS_GRAYWOLF_HTTP_PORT}" \
            --credential-file /etc/pcs/aprs/graywolf-admin.json \
            --callsign "${PCS_APRS_CALLSIGN}"; then
        echo "ERROR: Graywolf activation failed; restoring the staged database and PTT guard." >&2
        sudo systemctl disable --now graywolf.service >/dev/null 2>&1 || true
        sudo install -o graywolf -g graywolf -m 0640 "${backup_file}" /var/lib/graywolf/graywolf.db
        sudo systemctl mask graywolf.service >/dev/null
        sudo systemctl enable --now pcs-aprs-ptt-safe.service >/dev/null 2>&1 || true
        return 1
    fi

    sudo systemctl enable graywolf.service
    set_install_config_value "PCS_APRS_ENGINE" "graywolf"
    set_install_config_value "PCS_APRS_ENGINE_STAGED" "graywolf"
    set_install_config_value "PCS_SETUP_APRS" "yes"
    set_install_config_value "PCS_APRS_ACTIVE_MODE" "tx"
    set_install_config_value "PCS_APRS_TX_ENABLED" "yes"
    printf 'graywolf=%s\nhttp=%s:%s\nstate=active\nbackup=%s\n' \
        "${GRAYWOLF_VERSION}" "${PCS_GRAYWOLF_HTTP_ADDRESS}" "${PCS_GRAYWOLF_HTTP_PORT}" "${backup_file}" \
        | sudo tee "${ACTIVE_MARKER}" >/dev/null
    sudo chmod 0600 "${ACTIVE_MARKER}"
    echo "Graywolf is the selected active PCS APRS engine; Dire Wolf remains installed and masked for rollback."
}

rollback_direwolf() {
    local backup_file

    require_normal_user
    ensure_sudo
    backup_file="$(sudo find /var/backups/pcs-aprs -maxdepth 1 -type f -name 'graywolf.db.pre-activation.*' -printf '%T@ %p\n' 2>/dev/null \
        | sort -nr | awk 'NR==1 {$1=""; sub(/^ /, ""); print}')"
    [[ -n "${backup_file}" ]] || { echo "ERROR: no pre-activation Graywolf backup exists." >&2; return 1; }
    sudo systemctl disable --now graywolf.service >/dev/null 2>&1 || true
    sudo systemctl mask graywolf.service >/dev/null
    sudo install -o graywolf -g graywolf -m 0640 "${backup_file}" /var/lib/graywolf/graywolf.db
    sudo systemctl enable --now pcs-aprs-ptt-safe.service >/dev/null 2>&1
    sudo "${PTT_SAFE_DST}" --check
    sudo systemctl unmask direwolf.service >/dev/null
    sudo systemctl enable --now direwolf.service
    set_install_config_value "PCS_APRS_ENGINE" "direwolf"
    set_install_config_value "PCS_SETUP_APRS" "yes"
    set_install_config_value "PCS_APRS_ACTIVE_MODE" "tx"
    sudo rm -f "${ACTIVE_MARKER}"
    echo "Dire Wolf rollback completed; Graywolf is stopped and its staged database was restored."
}

case "${MODE}" in
    --prepare)
        prepare
        ;;
    --check)
        show_check
        ;;
    --capabilities)
        show_capabilities
        ;;
    --activate)
        activate
        ;;
    --rollback-direwolf)
        rollback_direwolf
        ;;
    -h|--help)
        usage
        ;;
    *)
        usage >&2
        exit 2
        ;;
esac
